var supportsWoff = (function( win ){
    if( !( "FontFace" in win ) ) {
        return false;
    }

    var f = new FontFace('t', 'url( "data:application/font-woff;base64,d09GRgABAAAAAAHgAAoAAAAAAggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABPUy8yAAAA9AAAABgAAABOBKQEQWNtYXAAAAEMAAAAJgAAACwADABzZ2x5ZgAAATQAAAAUAAAAFAgBOQJoZWFkAAABSAAAAC8AAAA2Dkdn0mhoZWEAAAF4AAAAFQAAACQIAQQDaG10eAAAAZAAAAAIAAAACAQAAABsb2NhAAABmAAAAAYAAAAGAAoAAG1heHAAAAGgAAAAEwAAACAABAACbmFtZQAAAbQAAAAeAAAAIAAjCF5wb3N0AAAB1AAAAAwAAAAgAAMAAHjaY2AAghQGRgZygQODAwuYASIBI1EA7njaY2BgYGRgBmIGBh4GFgYFIM0ChCC+w///EPL/QTCfAQBNfgZ8AAAAAQAAAAAEAAQAAAEAADEBBAAEAHjaY2BkYGAA4nBby/fx/DZfOZhYGEDgQlr1axB96fSyTyCahQEizsAEIgAb7wlHAHjaY2BkYGBhAAE4yciACpgAAZIAEQAAAAAAAAAEAAAAAAAAAAAKAAB42mNgZGBgYAJCEI0FAAAAvgAHAHjaY2BgYGKQY2BmYGThZGAEshmgbCYw2wEABjMAigAAeNpjYGbACwAAfQAE" ) format( "woff" )', {});
    f.load()['catch'](function() {});

    return f.status == 'loading' || f.status == 'loaded';
})( this );
